<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [2]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
import numpy as np
n=np.array(list_temperature)
print(n)

[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


In [2]:
#prctc
import numpy as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
c=np.array(list_temperature)
c

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [4]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
n=np.array(weights)
n[n>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

In [3]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
n1=np.array(weights)
n1[n1>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [7]:
n3=np.random.randint(20,40,10)
print(n3)

[38 38 33 39 25 28 38 24 27 24]


In [9]:
np.random.seed(24)
n4=np.random.randint(20,40,10)
print(n4)

[22 23 20 37 37 21 24 35 24 35]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
n=np.array([1,2,3,4,5])
n**5

array([   1,   32,  243, 1024, 3125], dtype=int32)

In [13]:
n4=np.arange(1,6)
n4

array([1, 2, 3, 4, 5])

In [24]:
n5=n4**5
print(n5)

[   1   32  243 1024 3125]


In [29]:
t= np.arange(1,6)**5
print(t)

[   1   32  243 1024 3125]


In [30]:
np.power(n4,5)

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
n=np.arange(51,101,2)
n

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

In [16]:
n5=np.arange(50,101)
n5[n5%2==1]

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [10]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
n=np.array(A)
print(n)
np.sum(n,axis=0)

[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]


array([15, 25, 13])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [14]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
n=np.array(num)
n[n%8] #conditinal accessing
n%8 #real opertn

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

In [20]:
import numpy as np
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
nm=np.array(num)
nm

array([42, 87, 90, 14, 32, 75, 61, 80, 92])

In [25]:
print(nm%8)

[2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
n7=np.random.randint(20,45,20)
n7

array([40, 22, 34, 32, 26, 20, 30, 24, 34, 43, 22, 38, 37, 41, 42, 41, 42,
       25, 28, 27])

In [6]:
n8=np.reshape(n7,(5,4))
print(n8)

[[40 22 34 32]
 [26 20 30 24]
 [34 43 22 38]
 [37 41 42 41]
 [42 25 28 27]]


In [51]:
a = np.arange(1,21).reshape(2,10)
print(a)
a[0,0:5]


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


array([1, 2, 3, 4, 5])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [43]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]

p=np.array(prices_monday)
r=np.array(prices_tuesday)
print(np.intersect1d(p,r))

[10 50]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [45]:

weights = [57, 69, 54, 65 ,71, 62, 56]

#list of heights (in m)<br>
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

w = np.array(weights)
h = np.array(heights)

BMI = w / h**2
BMI

np.round(BMI,2)

array([22.55, 22.53, 19.6 , 21.47, 26.4 , 20.96, 23.92])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [13]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
n=np.array(array1)
np.insert(n,axis=0,[5,7])

SyntaxError: positional argument follows keyword argument (<ipython-input-13-41aa9bfaf475>, line 3)

In [32]:
f= np.array([[[3, 4], [8, 2],[5, 9]]])
f= f.flatten()
g= np.append(f, [5,7]).reshape((1,4,2))
g


array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
import numpy as np
b = np.identity(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [59]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
nk=np.array(M)
nk


array([[15, 17, 45, 56],
       [ 7, 42, 15, 63],
       [54,  3, 61, 41],
       [ 0, 87, 16, 20]])

In [60]:
nk.T

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [11]:
A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]
n1=np.array(A1)
n2=np.array(A2)
n10=np.vstack((n1,n2))
print(n10)

[[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [13]:
A1a = [[-81, 75, 40], [27, 67, 52]]

A2a = [[15, 54], [39, 56]]

n1a=np.array(A1a)
n2a=np.array(A2a)
n11=np.hstack((n1a,n2a))
print(n11)

[[-81  75  40  15  54]
 [ 27  67  52  39  56]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [19]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
a=np.array(A)
print(a)


[[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]]


In [24]:
nk=np.vsplit(a,3)
print(nk)

[array([[ 4,  7],
       [ 2, -3]]), array([[8, 1],
       [0, 9]]), array([[ 5, -1],
       [ 8,  3]])]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [25]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
b=np.array(B)
print(b)

[[ 8  7  0  9]
 [ 2 -3  5 10]
 [ 8  5 -1  3]]


In [28]:
bsplit=np.hsplit(b,2)
print(bsplit)

[array([[ 8,  7],
       [ 2, -3],
       [ 8,  5]]), array([[ 0,  9],
       [ 5, 10],
       [-1,  3]])]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [29]:

l1 = np.array([45, 67, 56, 71, 54, 62, 56])
l2 = np.array([21, 52, 64, 10, 49, 74, 26])
f= np.array([[i,j] for i,j in zip(l1,l2)])
f

array([[45, 21],
       [67, 52],
       [56, 64],
       [71, 10],
       [54, 49],
       [62, 74],
       [56, 26]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [4]:
import numpy as np
numbers = [6, 5, 3, 15]
l=[]
for x in numbers:
    l.append(((2*x)-1)/(x+5))
print(l)
n=np.array(l)
print(n)

[1.0, 0.9, 0.625, 1.45]
[1.    0.9   0.625 1.45 ]


In [31]:
n = np.array([6, 5, 3, 15])
s= np.array([])
for i,j in enumerate(n):
      s= np.insert(s, i, ((2*j-1)/(j+5)))
s

array([1.   , 0.9  , 0.625, 1.45 ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [62]:
n = int(input('Enter the element..'))
l = []
for i in range(1,n+1):
    f = int(input('Enter the element {}'.format(i)))
    l.append(i)
l
np.diag(l)


Enter the element..5
Enter the element 12
Enter the element 26
Enter the element 35
Enter the element 46
Enter the element 57


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [2]:
import numpy as np
n = int(input('Enter the element..'))
l = []
for i in range(1,n+1):
    f = int(input('Enter the element'))
    l.append(f)
l
np.diag(l)


Enter the element..3
Enter the element2
Enter the element1
Enter the element4


array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 4]])

In [63]:
np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])